# Generated by Django 5.0.6 on 2025-04-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_customerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='service',
            field=models.TextField(),
        ),
    ]
