# Generated by Django 5.0.6 on 2025-05-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_customerrequest_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
