# Generated by Django 5.0.6 on 2025-05-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_customerrequest_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
